# Configuration for Dependency Review Action
# https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-dependency-review

# Vulnerabilities with these severities will cause the action to fail
fail_on_severity: 'critical'

# Allow these vulnerabilities (by GHSA ID)
# allow_ghsas:
  # Example: - GHSA-abcd-1234-5678

# Block these dependencies
# deny_packages:
  # Example for npm packages
  # - name: "lodash"
  #   version: "<4.17.21"

# Allow only these licenses
# allow_licenses:
#   - MIT
#   - Apache-2.0
#   - BSD-2-Clause
#   - BSD-3-Clause
#   - ISC
#   - CC0-1.0

# # Deny these licenses
# deny_licenses:
#   - GPL-2.0
#   - GPL-3.0
#   - AGPL-1.0

# Configure vulnerability database
vulnerability_check: true
license_check: true
