name: Update GW2 Data on Pages

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: client

      - name: Fetch GW2 achievement data
        run: npm run fetch:gw2-achievement-data
        working-directory: client

      - name: Download and extract latest deployed site artifact
        id: download_artifact
        run: |
          set -e
          mkdir -p _site
          # Get the latest deployment ID
          DEPLOYMENT_ID=$(gh api repos/${{ github.repository }}/deployments --jq '.[0].id')
          # Get the artifact download URL
          ARTIFACT_URL=$(gh api repos/${{ github.repository }}/deployments/$DEPLOYMENT_ID/artifacts --jq '.artifacts[0].archive_download_url')
          # Download the artifact as site-artifact.zip
          curl -L -o site-artifact.zip -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$ARTIFACT_URL"
          # Unzip to extract artifact.tar
          unzip -q site-artifact.zip
          # Extract artifact.tar into _site/
          tar -xvf artifact.tar -C _site

      - name: Copy new data files into site
        run: |
          mkdir -p _site/data
          cp client/public/data/*.json _site/data/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 