name: Project Automation

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened, ready_for_review]

# Minimal permissions
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  add-to-project:          
    name: Add to Project Board
    runs-on: ubuntu-latest
    if: github.repository_owner == 'tadthewonderdog' # Only run in your org
    steps:
      - name: Add item to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/tadthewonderdog/projects/2/
          github-token: ${{ secrets.GITHUB_TOKEN }} # Use built-in token instead of PAT
          labeled: bug,enhancement,documentation # Only add items with these labels
